version: "3.8"

services:
  mariadb:
    image: mariadb:user
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file :
      - .env
    networks :
      - inception
    restart: on-failure
  nginx:
    image: nginx:user
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: on-failure
  wordpress:
    image: wordpress:user
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    env_file :
      - .env
    networks:
      - inception
    restart: on-failure
  redis:
    image: redis:user
    container_name: redis
    build: ./requirements/bonus/redis
    depends_on:
      - mariadb
    networks:
      - inception
    restart: on-failure

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/${USER}/data/mariadb
      o : bind
      type : none
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/${USER}/data/wordpress
      o : bind
      type : none

networks:
  inception:
    name: inception
