version: "3.8"

services:
  mariadb:
    image: mariadb:user
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file :
      - .env
    networks :
      - inception
    restart: on-failure
  nginx:
    image: nginx:user
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/web
    networks:
      - inception
    restart: on-failure
  wordpress:
    image: wordpress:user
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/web
    env_file :
      - .env
    networks:
      - inception
    restart: on-failure
  redis:
    image: redis:user
    container_name: redis
    build: ./requirements/bonus/redis
    depends_on:
      - mariadb
    networks:
      - inception
    restart: on-failure
  ftp:
    image: ftp:user
    container_name: ftp
    build: ./requirements/bonus/ftp
    depends_on:
      - wordpress
    ports:
      - "21:21"
      - "8130-8140:8130-8140"
    volumes:
      - wordpress:/var/www/web
    env_file:
      - .env
    networks:
      - inception
    restart: on-failure
  staticpage:
    image: staticpage:user
    container_name: staticpage
    build: ./requirements/bonus/staticpage/
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/web
    networks:
      - inception
  adminer:
    image: adminer:user
    container_name: adminer
    build: ./requirements/bonus/adminer/
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/web
    networks:
      - inception
  portainer:
    image: portainer:user
    container_name: portainer
    build: ./requirements/bonus/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9443:9443"
    privileged: true
    networks:
      - inception
    restart: on-failure

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/${USER}/data/mariadb
      o : bind
      type : none
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/${USER}/data/web
      o : bind
      type : none

networks:
  inception:
    name: inception
